#     ****  (Need not be generated again unless running on different files ****
import FileSeparation
import Features
import pickle
import glob2

fs = FileSeparation.FileExtension()
fg = Features.FeatureGeneration()

# ---- separate files
c_files = fg.ExtractFiles('../../../data/c/**','c')
i_files = fg.ExtractFiles('../../../data/c/**','i')
filenames = c_files + i_files

for filename in filenames:
	filename = '../../..'+filename
	fg.RunTool1(filename,'../txt/features_tool1.txt','../txt/output_metrics1.txt')
	fg.RunTool2(filename,'../txt/features_tool2.txt')

# ---- formatting features generated above
with open('../txt/features_tool1.txt','r') as f:
	content1 = f.readlines()

content_tool1 = [x.strip() for x in content1]
feature_dict_tool1 = fg.Formatting(content_tool1, len(content_tool1), ' ')

with open('../txt/features_tool2.txt','r') as g:
	content2 = g.readlines()

content_tool2 = [x.strip() for x in content2]
feature_dict_tool2 = fg.Formatting(content_tool2,len(content_tool2), '\t')

# ---- merging feature vectors generated by two tools based on FILENAME
merged_dict = fg.MergeFeatures(feature_dict_tool1, feature_dict_tool2)

# ---- writing the final features to a file (use pickle.load() to load this file directly)
with open('../txt/FinalFeatures.txt','w') as f:
	pickle.dump(merged_dict,f)
